```{r}
library(tidyverse)
library(readxl)
library(stringr)
library(writexl)
library(ggthemes)

monster_books <- read_excel("Saved Data Files/Complete_Monster_List.xlsx")
```

# Data validating and Tidying 

```{r}
# Dropping duplicate observations (same book in same staff list) 

monster_books <- monster_books %>%
  distinct(Link, `Staff List Name`, .keep_all = TRUE)  # columns where we drop duplicates, .keep_all function keeps all variables 

#save the df back to the excel file if need be, no need to constatnly be removing the duplicate rows 
#write_xlsx(monster_books, "Saved Data Files/monster_books_edited.xlsx")
```


```{r}
# Grouping by staff list to ensure we're getting them all 
monster_books %>% group_by(`Staff List Name`) %>% summarise(n=n())

# How many staff lists are we getting?
sl_num <- length(unique(monster_books$`Staff List Name`))

cat(sl_num, "unique staff lists scrapped")

# Investigating specific staff lists 
monster_books %>% filter(`Staff List Name` == "Oh, how we love you October!")
```


```{r}
# Finding all the duplicate books and their various staff lists 
duplicate_books <- monster_books %>% group_by(Link) %>% filter(n()> 1) %>% summarise(Title, `Item Type`, `Staff List Name`, SL_Link, n = n())

#Counting the total number of duplicate books in our df 
length(unique(duplicate_books$Link))

duplicate_books <- arrange(duplicate_books, Title, `Staff List Name`) # The more appearances here, the more popular the book?
```


```{r}
# Tackling the rating variable 
rating_str <- "4.2 out of 5 stars, based on 83 ratings"

str_split(rating_str, pattern = " ")[[1]][8]
str_split(rating_str, " ")[[1]][1]

# idk why this string pattern doesn't work grrrrrrrrrrrrrrrrrrrr
monster_books <- monster_books %>%
  mutate(num_rate = ifelse(str_split(monster_books$Rating, pattern = " ")[[1]][8] != 0, str_split(monster_books$Rating, " ")[[1]][1], NULL))



# Pattern that extracts either a decimal/integer as the first number. Don't need second number because it's always 5
# d represents any digit 0-9, | is the or operator that we're looking for a decimal or integer.
pattern <- "\\d+\\.\\d+|\\d+" 

rating <- as.numeric(str_extract(rating_str, pattern)) # Make it in a numeric variable because why not?

rating
```




# Wrangling the core books 

```{r}
# find core books that I've already scrapped within staff lists and then getting rid of the original core row

monster_books_woc <- monster_books %>%  filter(!(`Broad Genre` %in% c("Adult Core", "Teen Core", "Youth Core", "Picture Book Core")))
the_already_core <- monster_books_woc %>% filter(str_detect(`Specific Genre`, "KDL Core") | str_detect(Subject, "KDL Core")) %>% pull(Title)
the_already_core <- unique(the_already_core)


monster_books_ac <- monster_books %>% filter(`Broad Genre` %in% c("Adult Core", "Teen Core", "Youth Core", "Picture Book Core"))

inte <- 0

for (book in monster_books_ac$Title) {
  if (!(book %in% the_already_core)){
    print(book)
    #inte <- inte + 1
    #cat("Book:", book, "| Count:", inte, "\n")
    monster_books_woc <- rbind(monster_books_woc, monster_books_ac[monster_books_ac$Title == book, ])
    monster_books_woc$`Broad Genre`
  }
}


# Checking the results
duplicate_books <- monster_books_woc %>% group_by(Link) %>% filter(n()> 1) %>% summarise(Title, `Item Type`, `Staff List Name`, SL_Link, n = n())

#Goes through each valuable core book in the df and attaches the core label in the Broad Genre variable
monster_books <- monster_books_woc

# Append string "Core" to the `Broad Genre` variable
monster_books <- monster_books %>%
  mutate(`Broad Genre` = if_else(str_detect(Subject, "KDL Core") & !str_detect(`Broad Genre`, "Core"),
                                  paste(`Broad Genre`, "Core", sep = ", "), `Broad Genre`))
```


```{r}
# remove excess dfs and lists 
rm(monster_books_woc, the_core, monster_books_ac, inte, duplicate_books)

#write_xlsx(monster_books, "Saved Data Files/monster_books_edited.xlsx")
```


# Data Analysis Part 

## Working with numeric variables (distributions)


```{r}
# we only want 1 observation per book when looking at book statistics 
monster_books <- monster_books %>%
  distinct(Link, .keep_all = TRUE) 

length(unique(monster_books$Link)) # all unique


#boxplots w/ filtering 

monster_books %>% filter(Holds < 3 &  `Item Count` < 20) %>%  
  ggplot(aes(`Item Count`)) + 
  geom_boxplot() 

# Summary statistics for our numeric variables 
summary(monster_books$Holds)
summary(monster_books$`Item Count`)

# Audiance
monster_books %>% ggplot(aes(Audiance)) + 
  geom_bar(color = "black", fill = "red") +
  scale_y_continuous(breaks = seq(0, 1200, by = 100),
                      limits = c(0, 1200)) +
  labs(title = "Audiance",
       y= "Count") +

  theme_clean()


item_type_df <- monster_books %>% group_by(`Item Type`) %>% summarise(count = n())

item_type_df %>% mutate(`Item Type` = fct_reorder(`Item Type`, desc(count))) %>% # fct_reorder function to reorder the Item Type based on count 
  filter(!`Item Type` %in% c("Book", "Unknown")) %>%     # Quick filter statement for increased clarity
  ggplot(aes(`Item Type`, count)) + 
  geom_bar(stat = 'identity',color = "black", fill = "red") +
  #scale_y_continuous(breaks = seq(0, 1200, by = 100),
  #                    limits = c(0, 1200)) +
  labs(title = "Item Type",
       y= "Count") +

  theme_clean() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

# Broad Genre
monster_books %>% group_by(`Broad Genre`) %>% summarise(count = n()) %>%
  mutate(`Broad Genre` = fct_reorder(`Broad Genre`, desc(count))) %>%
  ggplot(aes(`Broad Genre`, count)) + 
  geom_bar(stat = 'identity', color = "black", fill = "red") +
  #scale_y_continuous(breaks = seq(0, 1200, by = 100),
  #                    limits = c(0, 1200)) +
  labs(title = "Audiance",
       y= "Count") +

  theme_clean() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```



```{r}
# Status and Item type counts 

monster_books %>% group_by(`Item Type`) %>% summarise(count = n())%>% arrange(desc(count))

monster_books %>% group_by(Status) %>% summarise(count = n())%>% arrange(desc(count))
```


## Categorical Variable analyiss + string parsing 


```{r}
# Testing for how to parse subject and genre columns 

subject <- "Itliong, Larry, 1913-1977 — Juvenile literature, United Farm Workers of America — History — Juvenile literature, Labor leaders — United States — Biography — Juvenile literature, Filipino Americans — Biography — Juvenile literature, Agricultural laborers — Labor unions — United States — History — Biography — Juvenile literature, Discrimination - Kids, Southern Asian/Indian - Kids, Asian American - Kids"

beep <- unlist(str_split(subject, pattern = ",")) # using unlist here creates a character vector from a list (simpler indexing)
```



######################### Sheri Data set #####################################
```{r}
library(tidyverse)
library(readxl)
library(stringr)
library(writexl)
library(ggthemes)

kdl_report <- read_excel("Saved Data Files/Sheri Report.xlsx") %>% na.omit()
```

```{r}
kdl_report$ISBN <- str_remove_all(kdl_report$ISBN, "i")
kdl_report <- kdl_report %>% filter(str_starts(ISBN, "9")) #filter to find all odd ISBN's filter(!str_starts(ISBN, "9.*"))

kdl_report$title <- str_replace_all(kdl_report$title, "/", "")

kdl_report$call_num <- str_to_title(kdl_report$call_num)



# Creating audience variable 
kdl_report <- kdl_report %>% 
  mutate(audience = case_when(str_detect(call_num, "J ") ~ "J",
                              str_detect(call_num, "Teen") ~ "TEEN",
                              str_detect(call_num, "Je") ~ "JE",
                              str_detect(call_num, "Er") ~ "ER",
                              str_detect(call_num, "Jnf") ~ "JNF",
                              str_detect(call_num, "\\bE\\s") ~ "E", # making the search for E case sensitive fixes it pull adult items like tcrime
                              str_detect(call_num, "PB BOARD") ~ "Board",
                              TRUE ~ "Adult")) 
```


```{r}
#save the modified sheri report back to excel to load up in python

#write_xlsx(kdl_report, "Saved Data Files/kdl_report_edited.xlsx")
```




```{r eval=FALSE, include=FALSE}
# Add a unique ID column to each book (don't need this because link is unique)

monster_books$book_id <- sapply(monster_books$Link, function(url) {
  
  # Use str_split to split the URL by "/"
  id_number <- str_split(url, pattern = "/")[[1]][6]
  
  return(id_number)
})
```